# Generated by Django 4.1.6 on 2023-02-06 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_entregables_estudiante_profesor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entregables',
            name='apellido',
        ),
    ]
