# Generated by Django 4.1.6 on 2023-02-20 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_remove_entregables_apellido'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='comision',
            field=models.IntegerField(default=23),
        ),
    ]
