# Generated by Django 4.1.6 on 2023-02-20 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_curso_comision'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregables',
            name='entregado',
            field=models.CharField(default='si', max_length=50),
        ),
        migrations.AddField(
            model_name='profesor',
            name='edad',
            field=models.IntegerField(default=21),
        ),
    ]
