# Generated by Django 4.1.6 on 2023-02-22 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0005_entregables_entregado_profesor_edad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entregables',
            old_name='fechaEntrga',
            new_name='fechaEntrega',
        ),
    ]
